project_id = "hyoiixnnppjhhxxovmte"

[functions.firecrawl-scrape]
verify_jwt = false

[functions.firecrawl-search]
verify_jwt = false

[functions.firecrawl-map]
verify_jwt = false

[functions.firecrawl-crawl]
verify_jwt = false

[functions.cleanup-firecrawl-logs]
verify_jwt = false
